// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    users,
    portalApplicationCategories,
    portalApplications,
    portalApplicationFavorites,
    students,
    semesters,
    courses,
    departments,
    teachers,
    classes,
    classrooms,
    courseOfferings,
    teacherSemesters,
    courseOfferingTeachers,
    courseOfferingClasses,
    courseOfferingStudents,
    schedules,
    syllabuses,
    syllabusSections,
    materials,
    teacherOfficeHours,
    scores,
    userSemesterSummaries,
    userSemesterSummaryTutors,
    userSemesterSummaryCadreRoles,
    userSemesterRankings,
    calendarEvents,
    courseOfferingOverviews,
    courseTableSlots,
    scoreDetails,
    userAcademicSummaries,
    userRegistrations,
    classSemester,
    courseOfferingCourseCode,
    courseOfferingSemester,
    scheduleCourseOffering,
    materialCourseOffering,
    teacherSemesterSemester,
    teacherOfficeHourTeacherSemester,
    scoreUser,
    userSemesterSummaryUser,
  ];
  late final Shape0 users = Shape0(
    source: i0.VersionedTable(
      entityName: 'users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 portalApplicationCategories = Shape1(
    source: i0.VersionedTable(
      entityName: 'portal_application_categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(user, distinguished_name)'],
      columns: [
        _column_0,
        _column_17,
        _column_18,
        _column_3,
        _column_4,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 portalApplications = Shape2(
    source: i0.VersionedTable(
      entityName: 'portal_applications',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(category, code)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_3,
        _column_4,
        _column_22,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 portalApplicationFavorites = Shape3(
    source: i0.VersionedTable(
      entityName: 'portal_application_favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user, application_code)'],
      columns: [_column_17, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 students = Shape4(
    source: i0.VersionedTable(
      entityName: 'students',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_2, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 semesters = Shape5(
    source: i0.VersionedTable(
      entityName: 'semesters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(year, term)'],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 courses = Shape6(
    source: i0.VersionedTable(
      entityName: 'courses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_30,
        _column_31,
        _column_32,
        _column_3,
        _column_4,
        _column_33,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 departments = Shape7(
    source: i0.VersionedTable(
      entityName: 'departments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_30, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 teachers = Shape8(
    source: i0.VersionedTable(
      entityName: 'teachers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_30, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 classes = Shape9(
    source: i0.VersionedTable(
      entityName: 'classes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(code, semester)'],
      columns: [
        _column_0,
        _column_1,
        _column_21,
        _column_35,
        _column_3,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 classrooms = Shape10(
    source: i0.VersionedTable(
      entityName: 'classrooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_30, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 courseOfferings = Shape11(
    source: i0.VersionedTable(
      entityName: 'course_offerings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_36,
        _column_35,
        _column_37,
        _column_3,
        _column_4,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 teacherSemesters = Shape12(
    source: i0.VersionedTable(
      entityName: 'teacher_semesters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(teacher, semester)'],
      columns: [
        _column_0,
        _column_1,
        _column_50,
        _column_35,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 courseOfferingTeachers = Shape13(
    source: i0.VersionedTable(
      entityName: 'course_offering_teachers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(course_offering, teacher_semester)'],
      columns: [_column_56, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 courseOfferingClasses = Shape14(
    source: i0.VersionedTable(
      entityName: 'course_offering_classes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(course_offering, class_entity)'],
      columns: [_column_56, _column_58],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 courseOfferingStudents = Shape15(
    source: i0.VersionedTable(
      entityName: 'course_offering_students',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(course_offering, student)'],
      columns: [_column_56, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 schedules = Shape16(
    source: i0.VersionedTable(
      entityName: 'schedules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(course_offering, day_of_week, period)'],
      columns: [_column_0, _column_56, _column_60, _column_61, _column_62],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 syllabuses = Shape17(
    source: i0.VersionedTable(
      entityName: 'syllabuses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(course_offering, teacher, language)'],
      columns: [
        _column_0,
        _column_56,
        _column_50,
        _column_63,
        _column_64,
        _column_65,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 syllabusSections = Shape18(
    source: i0.VersionedTable(
      entityName: 'syllabus_sections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(syllabus, position)'],
      columns: [_column_0, _column_66, _column_67, _column_68, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 materials = Shape19(
    source: i0.VersionedTable(
      entityName: 'materials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(course_offering, href)'],
      columns: [
        _column_0,
        _column_56,
        _column_53,
        _column_69,
        _column_70,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 teacherOfficeHours = Shape20(
    source: i0.VersionedTable(
      entityName: 'teacher_office_hours',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(teacher_semester, day_of_week, start_hour, start_minute)',
      ],
      columns: [
        _column_0,
        _column_57,
        _column_60,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 scores = Shape21(
    source: i0.VersionedTable(
      entityName: 'scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_35,
        _column_76,
        _column_77,
        _column_78,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 userSemesterSummaries = Shape22(
    source: i0.VersionedTable(
      entityName: 'user_semester_summaries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(user, semester)'],
      columns: [
        _column_0,
        _column_17,
        _column_35,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 userSemesterSummaryTutors = Shape23(
    source: i0.VersionedTable(
      entityName: 'user_semester_summary_tutors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(summary, teacher_semester)'],
      columns: [_column_89, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape24 userSemesterSummaryCadreRoles = Shape24(
    source: i0.VersionedTable(
      entityName: 'user_semester_summary_cadre_roles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(summary, role)'],
      columns: [_column_0, _column_89, _column_90],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape25 userSemesterRankings = Shape25(
    source: i0.VersionedTable(
      entityName: 'user_semester_rankings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(summary, ranking_type)'],
      columns: [
        _column_89,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape26 calendarEvents = Shape26(
    source: i0.VersionedTable(
      entityName: 'calendar_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_96,
        _column_97,
        _column_98,
        _column_99,
        _column_53,
        _column_100,
        _column_68,
        _column_101,
        _column_102,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape27 courseOfferingOverviews = Shape27(
    source: i0.VersionedView(
      entityName: 'course_offering_overviews',
      createViewStmt: 'CREATE VIEW IF NOT EXISTS course_offering_overviews (id,course_code,semester,number,name_zh,name_en,credits,hours,phase,course_type,status,language,remarks,enrolled,withdrawn,fetched_at) AS SELECT t0.id AS id, t0.course_code AS course_code, t0.semester AS semester, t0.number AS number, COALESCE(t0.name_zh, t1.name_zh) AS name_zh, COALESCE(t0.name_en, t1.name_en) AS name_en, COALESCE(t0.credits, t1.credits) AS credits, COALESCE(t0.hours, t1.hours) AS hours, t0.phase AS phase, t0.course_type AS course_type, t0.status AS status, t0.language AS language, t0.remarks AS remarks, t0.enrolled AS enrolled, t0.withdrawn AS withdrawn, t0.fetched_at AS fetched_at FROM course_offerings AS t0 LEFT OUTER JOIN courses AS t1 ON t1.code = t0.course_code;',
      columns: [
        _column_103,
        _column_104,
        _column_105,
        _column_106,
        _column_107,
        _column_108,
        _column_109,
        _column_110,
        _column_111,
        _column_112,
        _column_113,
        _column_114,
        _column_115,
        _column_116,
        _column_117,
        _column_118,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape28 courseTableSlots = Shape28(
    source: i0.VersionedView(
      entityName: 'course_table_slots',
      createViewStmt: 'CREATE VIEW IF NOT EXISTS course_table_slots (id,number,semester,name_zh,name_en,credits,hours,day_of_week,period,classroom_name_zh,classroom_name_en) AS SELECT t1.id AS id, t1.number AS number, t1.semester AS semester, COALESCE(t1.name_zh, t2.name_zh) AS name_zh, COALESCE(t1.name_en, t2.name_en) AS name_en, COALESCE(t1.credits, t2.credits) AS credits, COALESCE(t1.hours, t2.hours) AS hours, t0.day_of_week AS day_of_week, t0.period AS period, t3.name_zh AS classroom_name_zh, t3.name_en AS classroom_name_en FROM schedules AS t0 INNER JOIN course_offerings AS t1 ON t1.id = t0.course_offering LEFT OUTER JOIN courses AS t2 ON t2.code = t1.course_code LEFT OUTER JOIN classrooms AS t3 ON t3.id = t0.classroom WHERE t1.in_course_table = 1;',
      columns: [
        _column_103,
        _column_106,
        _column_105,
        _column_107,
        _column_108,
        _column_109,
        _column_110,
        _column_119,
        _column_120,
        _column_121,
        _column_122,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape29 scoreDetails = Shape29(
    source: i0.VersionedView(
      entityName: 'score_details',
      createViewStmt: 'CREATE VIEW IF NOT EXISTS score_details (id,user,semester,score,status,code,name_zh,name_en,number) AS SELECT t0.id AS id, t0.user AS user, t0.semester AS semester, t0.score AS score, t0.status AS status, t1.code AS code, COALESCE(t2.name_zh, t1.name_zh) AS name_zh, COALESCE(t2.name_en, t1.name_en) AS name_en, t2.number AS number FROM scores AS t0 INNER JOIN courses AS t1 ON t1.id = t0.course LEFT OUTER JOIN course_offerings AS t2 ON t2.id = t0.course_offering;',
      columns: [
        _column_103,
        _column_123,
        _column_105,
        _column_124,
        _column_113,
        _column_125,
        _column_107,
        _column_108,
        _column_106,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape30 userAcademicSummaries = Shape30(
    source: i0.VersionedView(
      entityName: 'user_academic_summaries',
      createViewStmt: 'CREATE VIEW IF NOT EXISTS user_academic_summaries (id,user,semester,year,term,average,conduct,total_credits,credits_passed,note,gpa) AS SELECT t0.id AS id, t0.user AS user, t0.semester AS semester, t1.year AS year, t1.term AS term, t0.average AS average, t0.conduct AS conduct, t0.total_credits AS total_credits, t0.credits_passed AS credits_passed, t0.note AS note, t0.gpa AS gpa FROM user_semester_summaries AS t0 INNER JOIN semesters AS t1 ON t1.id = t0.semester;',
      columns: [
        _column_103,
        _column_123,
        _column_105,
        _column_126,
        _column_127,
        _column_128,
        _column_129,
        _column_130,
        _column_131,
        _column_132,
        _column_133,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape31 userRegistrations = Shape31(
    source: i0.VersionedView(
      entityName: 'user_registrations',
      createViewStmt: 'CREATE VIEW IF NOT EXISTS user_registrations (year,term,class_name,enrollment_status,graduated) AS SELECT t1.year AS year, t1.term AS term, t0.class_name AS class_name, t0.enrollment_status AS enrollment_status, t0.graduated AS graduated FROM user_semester_summaries AS t0 INNER JOIN semesters AS t1 ON t1.id = t0.semester;',
      columns: [
        _column_126,
        _column_127,
        _column_134,
        _column_135,
        _column_136,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index classSemester = i1.Index(
    'class_semester',
    'CREATE INDEX class_semester ON classes (semester)',
  );
  final i1.Index courseOfferingCourseCode = i1.Index(
    'course_offering_course_code',
    'CREATE INDEX course_offering_course_code ON course_offerings (course_code)',
  );
  final i1.Index courseOfferingSemester = i1.Index(
    'course_offering_semester',
    'CREATE INDEX course_offering_semester ON course_offerings (semester)',
  );
  final i1.Index scheduleCourseOffering = i1.Index(
    'schedule_course_offering',
    'CREATE INDEX schedule_course_offering ON schedules (course_offering)',
  );
  final i1.Index materialCourseOffering = i1.Index(
    'material_course_offering',
    'CREATE INDEX material_course_offering ON materials (course_offering)',
  );
  final i1.Index teacherSemesterSemester = i1.Index(
    'teacher_semester_semester',
    'CREATE INDEX teacher_semester_semester ON teacher_semesters (semester)',
  );
  final i1.Index teacherOfficeHourTeacherSemester = i1.Index(
    'teacher_office_hour_teacher_semester',
    'CREATE INDEX teacher_office_hour_teacher_semester ON teacher_office_hours (teacher_semester)',
  );
  final i1.Index scoreUser = i1.Index(
    'score_user',
    'CREATE INDEX score_user ON scores (user)',
  );
  final i1.Index userSemesterSummaryUser = i1.Index(
    'user_semester_summary_user',
    'CREATE INDEX user_semester_summary_user ON user_semester_summaries (user)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dateOfBirth =>
      columnsByName['date_of_birth']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get programZh =>
      columnsByName['program_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get programEn =>
      columnsByName['program_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get departmentZh =>
      columnsByName['department_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get departmentEn =>
      columnsByName['department_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatarFilename =>
      columnsByName['avatar_filename']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get passwordExpiresInDays =>
      columnsByName['password_expires_in_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semestersFetchedAt =>
      columnsByName['semesters_fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scoreDataFetchedAt =>
      columnsByName['score_data_fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get calendarFetchedAt =>
      columnsByName['calendar_fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get applicationCatalogFetchedAt =>
      columnsByName['application_catalog_fetched_at']!
          as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'student_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_zh',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'date_of_birth',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'program_zh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'program_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'department_zh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'department_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'avatar_filename',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'password_expires_in_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'semesters_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_data_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'calendar_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'application_catalog_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get user =>
      columnsByName['user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get distinguishedName =>
      columnsByName['distinguished_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'user',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES users(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'distinguished_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get category =>
      columnsByName['category']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iconUrl =>
      columnsByName['icon_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_20(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'category',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL REFERENCES portal_application_categories(id)ON DELETE CASCADE',
);
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get user =>
      columnsByName['user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get applicationCode =>
      columnsByName['application_code']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'application_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get term =>
      columnsByName['term']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inCourseSemesterList =>
      columnsByName['in_course_semester_list']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inScoreSemesterList =>
      columnsByName['in_score_semester_list']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseTableFetchedAt =>
      columnsByName['course_table_fetched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'term',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_course_semester_list',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (in_course_semester_list IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_score_semester_list',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (in_score_semester_list IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'course_table_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get credits =>
      columnsByName['credits']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hours =>
      columnsByName['hours']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descriptionZh =>
      columnsByName['description_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descriptionEn =>
      columnsByName['description_en']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credits',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hours',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description_zh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'semester',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES semesters(id)',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseCode =>
      columnsByName['course_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get number =>
      columnsByName['number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get credits =>
      columnsByName['credits']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hours =>
      columnsByName['hours']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get phase =>
      columnsByName['phase']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseType =>
      columnsByName['course_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remarks =>
      columnsByName['remarks']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inCourseTable =>
      columnsByName['in_course_table']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enrolled =>
      columnsByName['enrolled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get withdrawn =>
      columnsByName['withdrawn']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get studentRosterFetchedAt =>
      columnsByName['student_roster_fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get materialsFetchedAt =>
      columnsByName['materials_fetched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'course_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL UNIQUE',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credits',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hours',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'phase',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'course_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'remarks',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_course_table',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (in_course_table IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enrolled',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'withdrawn',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'student_roster_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'materials_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teacher =>
      columnsByName['teacher']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get department =>
      columnsByName['department']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get teachingHours =>
      columnsByName['teaching_hours']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get officeHoursNote =>
      columnsByName['office_hours_note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'teacher',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES teachers(id)',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'department',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES departments(id)',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_54(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'teaching_hours',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'office_hours_note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teacherSemester =>
      columnsByName['teacher_semester']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'course_offering',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES course_offerings(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'teacher_semester',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES teacher_semesters(id)',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get classEntity =>
      columnsByName['class_entity']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'class_entity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES classes(id)',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get student =>
      columnsByName['student']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'student',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES students(id)',
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dayOfWeek =>
      columnsByName['day_of_week']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get period =>
      columnsByName['period']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get classroom =>
      columnsByName['classroom']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'day_of_week',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'period',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'classroom',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES classrooms(id)',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teacher =>
      columnsByName['teacher']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syllabus =>
      columnsByName['syllabus']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'syllabus',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES syllabuses(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get href =>
      columnsByName['href']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iSchoolCourseId =>
      columnsByName['i_school_course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get streamable =>
      columnsByName['streamable']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'href',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'i_school_course_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'streamable',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (streamable IN (0, 1))',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teacherSemester =>
      columnsByName['teacher_semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dayOfWeek =>
      columnsByName['day_of_week']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startHour =>
      columnsByName['start_hour']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startMinute =>
      columnsByName['start_minute']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endHour =>
      columnsByName['end_hour']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endMinute =>
      columnsByName['end_minute']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_hour',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_minute',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_hour',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_minute',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get user =>
      columnsByName['user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get course =>
      columnsByName['course']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseOffering =>
      columnsByName['course_offering']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get score =>
      columnsByName['score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'course',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES courses(id)',
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'course_offering',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES course_offerings(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get user =>
      columnsByName['user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get average =>
      columnsByName['average']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get conduct =>
      columnsByName['conduct']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalCredits =>
      columnsByName['total_credits']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get creditsPassed =>
      columnsByName['credits_passed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get gpa =>
      columnsByName['gpa']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get className =>
      columnsByName['class_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get enrollmentStatus =>
      columnsByName['enrollment_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get registered =>
      columnsByName['registered']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graduated =>
      columnsByName['graduated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_79(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'average',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_80(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'conduct',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_81(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_credits',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_82(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credits_passed',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_84(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'gpa',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'class_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'enrollment_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'registered',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (registered IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'graduated',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (graduated IN (0, 1))',
    );

class Shape23 extends i0.VersionedTable {
  Shape23({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teacherSemester =>
      columnsByName['teacher_semester']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_89(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'summary',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES user_semester_summaries(id)ON DELETE CASCADE',
    );

class Shape24 extends i0.VersionedTable {
  Shape24({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape25 extends i0.VersionedTable {
  Shape25({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rankingType =>
      columnsByName['ranking_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get semesterRank =>
      columnsByName['semester_rank']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semesterTotal =>
      columnsByName['semester_total']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get grandTotalRank =>
      columnsByName['grand_total_rank']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get grandTotalTotal =>
      columnsByName['grand_total_total']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ranking_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_92(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'semester_rank',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'semester_total',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_94(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'grand_total_rank',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_95(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'grand_total_total',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape26 extends i0.VersionedTable {
  Shape26({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get portalId =>
      columnsByName['portal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get start =>
      columnsByName['start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get end =>
      columnsByName['end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get allDay =>
      columnsByName['all_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get place =>
      columnsByName['place']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerName =>
      columnsByName['owner_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get creatorName =>
      columnsByName['creator_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_96(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'portal_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_97(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_98(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_99(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'all_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (all_day IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_100(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'place',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_101(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_102(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'creator_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape27 extends i0.VersionedView {
  Shape27({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseCode =>
      columnsByName['course_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get number =>
      columnsByName['number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get credits =>
      columnsByName['credits']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hours =>
      columnsByName['hours']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get phase =>
      columnsByName['phase']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseType =>
      columnsByName['course_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remarks =>
      columnsByName['remarks']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enrolled =>
      columnsByName['enrolled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get withdrawn =>
      columnsByName['withdrawn']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_103(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_104(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'course_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_105(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'semester',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_106(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_107(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_zh',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_108(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_109(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credits',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_110(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hours',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_111(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'phase',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_112(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'course_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_113(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_114(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_115(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'remarks',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_116(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enrolled',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_117(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'withdrawn',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_118(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

class Shape28 extends i0.VersionedView {
  Shape28({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get number =>
      columnsByName['number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get credits =>
      columnsByName['credits']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hours =>
      columnsByName['hours']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dayOfWeek =>
      columnsByName['day_of_week']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get period =>
      columnsByName['period']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get classroomNameZh =>
      columnsByName['classroom_name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get classroomNameEn =>
      columnsByName['classroom_name_en']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_119(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'day_of_week',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_120(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'period',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_121(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'classroom_name_zh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_122(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'classroom_name_en',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape29 extends i0.VersionedView {
  Shape29({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get user =>
      columnsByName['user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get score =>
      columnsByName['score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameZh =>
      columnsByName['name_zh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameEn =>
      columnsByName['name_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get number =>
      columnsByName['number']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_123(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'user',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_124(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_125(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape30 extends i0.VersionedView {
  Shape30({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get user =>
      columnsByName['user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get term =>
      columnsByName['term']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get average =>
      columnsByName['average']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get conduct =>
      columnsByName['conduct']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalCredits =>
      columnsByName['total_credits']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get creditsPassed =>
      columnsByName['credits_passed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get gpa =>
      columnsByName['gpa']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_126(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_127(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'term',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_128(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'average',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_129(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'conduct',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_130(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_credits',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_131(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credits_passed',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_132(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_133(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'gpa',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape31 extends i0.VersionedView {
  Shape31({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get term =>
      columnsByName['term']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get className =>
      columnsByName['class_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get enrollmentStatus =>
      columnsByName['enrollment_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get graduated =>
      columnsByName['graduated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_134(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'class_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_135(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'enrollment_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_136(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'graduated',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
