include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**

plugins:
  riverpod_lint: 3.1.2
  prefer_shorthands: 0.4.7

formatter:
  trailing_commas: preserve

linter:
  rules:
    - always_use_package_imports
    - combinators_ordering
    - directives_ordering
    - unnecessary_library_directive
