targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            app_database: lib/database/database.dart
          schema_dir: lib/database/migrations/
          test_dir: test/database/
