// File generated by FlutterFire CLI.
// dart format off
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwy04VDvRscfjTPu2ShxLbB-_EyuezEhU',
    appId: '1:838220085712:android:a85cf2541699925c3be1d5',
    messagingSenderId: '838220085712',
    projectId: 'npc-tattoo',
    storageBucket: 'npc-tattoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_en-3_f7VONU8KA8zucI-tTgrsV_PJM',
    appId: '1:838220085712:ios:d5b7636cdc72fd603be1d5',
    messagingSenderId: '838220085712',
    projectId: 'npc-tattoo',
    storageBucket: 'npc-tattoo.firebasestorage.app',
    iosBundleId: 'club.ntut.tattoo',
  );
}
// dart format on
