// File generated by FlutterFire CLI.
// dart format off
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart' show appFlavor;

/// [FirebaseOptions] for the TAT Firebase projects (dev and prod).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ),
    };
  }

  static const String _env = String.fromEnvironment('ENV', defaultValue: '');
  static const String _flavor = String.fromEnvironment('FLAVOR', defaultValue: '');

  static bool get isDev =>
      _env == 'dev' ||
      _env == 'development' ||
      _env == 'staging' ||
      _flavor == 'dev' ||
      _flavor == 'staging' ||
      appFlavor == 'dev' ||
      appFlavor == 'staging';

  static FirebaseOptions get android => isDev ? androidDev : androidProd;

  static FirebaseOptions get ios => isDev ? iosDev : iosProd;

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyAJSD6_YkutviZvQvtjwNi5wAQaOAV7YDQ',
    appId: '1:596630117465:android:9d4275579e011f039f6548',
    messagingSenderId: '596630117465',
    projectId: 'npc-tattoo-prod',
    storageBucket: 'npc-tattoo-prod.firebasestorage.app',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyBQ03equalPQPzbD7Jxd9vGWHzrDU-AY0w',
    appId: '1:596630117465:ios:afd1697a77bcb95f9f6548',
    messagingSenderId: '596630117465',
    projectId: 'npc-tattoo-prod',
    storageBucket: 'npc-tattoo-prod.firebasestorage.app',
    iosBundleId: 'com.npc.tatFlutter',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyAwy04VDvRscfjTPu2ShxLbB-_EyuezEhU',
    appId: '1:838220085712:android:a85cf2541699925c3be1d5',
    messagingSenderId: '838220085712',
    projectId: 'npc-tattoo',
    storageBucket: 'npc-tattoo.firebasestorage.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyDp_en-3_f7VONU8KA8zucI-tTgrsV_PJM',
    appId: '1:838220085712:ios:d5b7636cdc72fd603be1d5',
    messagingSenderId: '838220085712',
    projectId: 'npc-tattoo',
    storageBucket: 'npc-tattoo.firebasestorage.app',
    iosBundleId: 'club.ntut.tattoo',
  );
}
// dart format on
