// File generated by FlutterFire CLI.
// dart format off
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [FirebaseOptions] for the TAT production Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSD6_YkutviZvQvtjwNi5wAQaOAV7YDQ',
    appId: '1:596630117465:android:9d4275579e011f039f6548',
    messagingSenderId: '596630117465',
    projectId: 'npc-tattoo-prod',
    storageBucket: 'npc-tattoo-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ03equalPQPzbD7Jxd9vGWHzrDU-AY0w',
    appId: '1:596630117465:ios:afd1697a77bcb95f9f6548',
    messagingSenderId: '596630117465',
    projectId: 'npc-tattoo-prod',
    storageBucket: 'npc-tattoo-prod.firebasestorage.app',
    iosBundleId: 'com.npc.tatFlutter',
  );
}
// dart format on
