name: Android Job Summary
description: Write Android build information to GitHub Job Summary

inputs:
  build_number:
    description: 'Build number'
    required: true
  type:
    description: 'Distribution type: firebase or playstore'
    required: true
    default: 'firebase'
  testing_uri:
    description: 'Install URI (required for firebase)'
    required: false

runs:
  using: composite
  steps:
    - name: Write Android Job Summary
      shell: bash
      run: |
        if [ "${{ inputs.type }}" == "firebase" ]; then
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
        ### Android (Firebase App Distribution)
        Build **${{ inputs.build_number }}** successfully uploaded to Firebase App Distribution.
        [Install build ${{ inputs.build_number }}](${{ inputs.testing_uri }})
        > **Note:** It may take a few minutes for the build to appear in the Firebase App after upload.
        EOF
        else
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
        ### Android (Google Play)
        Build **${{ inputs.build_number }}** successfully uploaded to Google Play.

        1. Open the Google Play Store on your Android device
        2. Select "Project Tattoo"
        3. Install or update to the latest build

        > **Note:** Manual build selection is not available in Google Play, so the latest approved build will be installed.
        > **Note:** It may take ~15 minutes for the build to appear in the Play Store after upload.
        EOF
        fi
