# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and sign release IPA"
  lane :build_ipa do
    setup_ci if is_ci

    match(
      type: "development",
      app_identifier: "club.ntut.tattoo",
      git_url: ENV["SIGNING_GIT_URL"],
      readonly: true
    )

    Dir.chdir("..") do
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "club.ntut.tattoo" => "match Development club.ntut.tattoo"
        }
      },
      output_directory: "../build/ios/ipa",
      output_name: "tattoo.ipa"
    )
  end
end
