name: Setup Project
description: Install development tools with mise and get dependencies

inputs:
  platform:
    description: The target platform (e.g., ios, android)

runs:
  using: composite
  steps:
    - name: Install mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      with:
        install_args: > 
          ${{ case(
            inputs.platform == 'android', 'flutter java',
            inputs.platform == 'ios', 'flutter ruby',
            'flutter'
          ) }}
        add_shims_to_path: false # Use direct bin paths

    - name: Verify Flutter version
      id: flutter-version
      if: ${{ inputs.platform == 'android' }}
      shell: bash
      run: |
        FLUTTER_VERSION=$(mise current flutter)
        if [ "$FLUTTER_VERSION" != "3.38.9" ]; then
          echo "::error::Flutter version has changed to $FLUTTER_VERSION. Please update cache paths accordingly."
          exit 1
        fi
        echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Gradle cache
      if: ${{ inputs.platform == 'android' }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Android SDK cache
      if: ${{ inputs.platform == 'android' }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
      with:
        key: ${{ runner.os }}-android-sdk-${{ steps.flutter-version.outputs.flutter_version }}
        # Update paths when updating Flutter version
        path: |
          /usr/local/lib/android/sdk/cmake/3.22.1
        restore-keys: |
          ${{ runner.os }}-android-sdk-

    - name: Select Xcode version
      if: ${{ inputs.platform == 'ios' }}
      shell: bash
      run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer

    - name: Setup Ruby
      if: ${{ inputs.platform == 'ios' }}
      uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
      with:
        bundler-cache: true

    - name: Setup CocoaPods cache
      if: ${{ inputs.platform == 'ios' }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
      with:
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        path: ios/Pods
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Setup Flutter pub cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
      with:
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        path: ~/.pub-cache
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Install Flutter dependencies
      shell: bash
      run: flutter pub get --enforce-lockfile
