name: Write Build Summary
description: Write build information to GitHub Job Summary

inputs:
  title:
    description: 'Summary title'
    required: true
  build_number:
    description: 'Build number'
    required: true
  commit_sha:
    description: 'Short commit SHA'
    required: true
  commit_message:
    description: 'Commit message'
    required: true

runs:
  using: composite
  steps:
    - name: Write Build Summary
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
      run: |
        cat >> "$GITHUB_STEP_SUMMARY" <<EOF
        ## ${{ inputs.title }}
        **Build Number:** ${{ inputs.build_number }}
        **Commit:** [$COMMIT_SHA](${{ github.server_url }}/${{ github.repository }}/commit/$COMMIT_SHA)
        **Message:** $COMMIT_MESSAGE
        EOF
