import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties
import java.io.File
import java.io.FileInputStream
import java.util.Base64

plugins {
    id("com.android.application")
    // START: FlutterFire Configuration
    // firebase plugins should be managed by the conditional apply below.
    // END: FlutterFire Configuration
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val repoRootDir: File = rootProject.projectDir.parentFile

// Fallback environment map (default development)
var dartEnvironmentVariables = mutableMapOf(
    "ENV" to "development",
    "FLAVOR" to "dev",
    "APP_CONFIG_NAME" to "Tattoo",
    "ANDROID_APPLICATION_ID" to "club.ntut.tattoo",
    "ANDROID_APP_LABEL" to "Tattoo",
    "ANDROID_RES_DIR" to "android/app/src/dev/res",
    "ANDROID_FIREBASE_CONFIG_PATH" to "android/app/google-services.json"
)

// 1. Read app.properties or AppConfig.xcconfig if generated by tool/credentials.dart
val appConfigFile = file("app.properties").takeIf { it.exists() }
    ?: rootProject.file("../ios/Flutter/AppConfig.xcconfig").takeIf { it.exists() }

appConfigFile?.let { cfgFile ->
    if (cfgFile.name.endsWith(".xcconfig")) {
        cfgFile.readLines().forEach { line ->
            val trimmed = line.trim()
            if (trimmed.isNotEmpty() && !trimmed.startsWith("//") && !trimmed.startsWith("#") && trimmed.contains("=")) {
                val parts = trimmed.split("=", limit = 2)
                val key = parts[0].trim()
                val value = parts[1].trim()
                when (key) {
                    "APP_CONFIG_NAME" -> dartEnvironmentVariables["ANDROID_APP_LABEL"] = value
                }
            }
        }
    } else {
        Properties().apply {
            FileInputStream(cfgFile).use { load(it) }
            getProperty("applicationId")?.let { dartEnvironmentVariables["ANDROID_APPLICATION_ID"] = it }
            getProperty("appLabel")?.let { dartEnvironmentVariables["ANDROID_APP_LABEL"] = it }
            getProperty("resDir")?.let { dartEnvironmentVariables["ANDROID_RES_DIR"] = it }
        }
    }
}

// 2. Decode dart-defines passed via Flutter CLI (--dart-define-from-file or --dart-define)
if (project.hasProperty("dart-defines")) {
    val dartDefines = project.property("dart-defines") as String
    dartDefines.split(",").forEach { entry ->
        val decodedEntry = String(Base64.getDecoder().decode(entry), Charsets.UTF_8)
        val pair = decodedEntry.split("=", limit = 2)
        if (pair.size == 2) {
            dartEnvironmentVariables[pair[0]] = pair[1]
        }
    }
}

val resolvedAppId = dartEnvironmentVariables["ANDROID_APPLICATION_ID"] ?: "club.ntut.tattoo"
val resolvedAppLabel = dartEnvironmentVariables["ANDROID_APP_LABEL"]
    ?: dartEnvironmentVariables["APP_CONFIG_NAME"]
    ?: "Tattoo"
val resDirPath = dartEnvironmentVariables["ANDROID_RES_DIR"] ?: "android/app/src/dev/res"
val androidResDir = File(repoRootDir, resDirPath)

// Copy google-services.json from ANDROID_FIREBASE_CONFIG_PATH if distinct and exists
tasks.register("copyGoogleServices") {
    val configPath = dartEnvironmentVariables["ANDROID_FIREBASE_CONFIG_PATH"] ?: "android/app/google-services.json"
    val sourceFile = File(repoRootDir, configPath)
    val targetFile = file("google-services.json")
    inputs.file(sourceFile)
    outputs.file(targetFile)
    doLast {
        if (sourceFile.exists() && sourceFile.canonicalPath != targetFile.canonicalPath) {
            sourceFile.copyTo(targetFile, overwrite = true)
            println("Copied google-services.json from ${sourceFile.relativeTo(repoRootDir)} to android/app/")
        }
    }
}

tasks.configureEach {
    if (name == "processDebugGoogleServices" || name == "processReleaseGoogleServices") {
        dependsOn("copyGoogleServices")
    }
}

android {
    namespace = "club.ntut.npc.tat"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        getByName("main") {
            res.srcDirs("src/main/res")
        }
        if (androidResDir.exists() && androidResDir.isDirectory && androidResDir.canonicalPath != file("src/main/res").canonicalPath) {
            getByName("release") {
                res.srcDirs("src/release/res", androidResDir)
            }
            getByName("debug") {
                res.srcDirs("src/debug/res", androidResDir)
            }
        }
    }

    defaultConfig {
        applicationId = resolvedAppId
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        manifestPlaceholders["appLabel"] = resolvedAppLabel
    }

    val keystorePropertiesFile = rootProject.file("key.properties")
    val keystoreProperties = Properties().apply {
        if (keystorePropertiesFile.exists()) {
            FileInputStream(keystorePropertiesFile).use { load(it) }
        }
    }

    signingConfigs {
        create("release") {
            storeFile = keystoreProperties["storeFile"]?.let { file(it.toString()) }
            storePassword = keystoreProperties["storePassword"]?.toString() ?: ""
            keyAlias = keystoreProperties["keyAlias"]?.toString() ?: ""
            keyPassword = keystoreProperties["keyPassword"]?.toString() ?: ""
        }
    }

    buildTypes {
        release {
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
        debug {
            applicationIdSuffix = ".debug"
        }
    }
}

// Conditionally apply google-services plugin to avoid mismatch errors in debug build
val isRelease = project.gradle.startParameter.taskNames.any {
    it.contains("release", ignoreCase = true) || it.contains("bundle", ignoreCase = true)
}
if (isRelease) {
    apply(plugin = "com.google.gms.google-services")
    apply(plugin = "com.google.firebase.crashlytics")
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.fromTarget("17")
    }
}

dependencies {
    implementation("androidx.core:core-splashscreen:1.2.0")
}

flutter {
    source = "../.."
}
